### ISSUE TITLE
Advise of proper placement of build steps in Travis YAML files

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/developer-manual#21]
From roboticslab-uc3m/kinematics-dynamics@677eeab:

> A build failure in 'before_script' marks the whole job as 'errored' and prevents from entering the following sections. On the other hand, errors within 'script' mark the job as 'failed', but will not cancel it right away. The point of this commit is to provide a means of distinguishing build/test failures and to abort the execution of test scripts if there are no binaries to link to.

```diff
diff --git a/.travis.yml b/.travis.yml
index 0d337c64..fcb3a142 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -49,12 +49,12 @@ install:
 
 before_script:
   - mkdir -p build && cd build
-
-script:
   - cmake .. -DENABLE_coverage=ON
   - make
   - sudo make install
   - sudo ldconfig
+
+script:
   - bin/testKdlSolver
   - bin/testKdlSolverFromFile
   - bin/testBasicCartesianControl
```

Reference: https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build.

**Comment by PeterBowman** [comment]
Note: https://github.com/roboticslab-uc3m/questions-and-answers/issues/48 ended in adopting a new template for YAML files ([sample](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/c9f194d48a36a1f7a2b9f689bd7646541807efbc/.travis.yml)).

**Comment by davidvelascogarcia** [comment]
I´m not sure if this issue is the best place to comment the problem that i had with `Travis CI` using a `docker` container with `Ubuntu 18.04` image but i can´t find another similar issue.
I´m trying to add `CI` to `tensorflow_cc` projects using `docker` images with `tensorflow_cc` pre-build, because `tensorflow_cc` build requires a lot of time and at the end get `Travis` timeout error. 
`Tensorflow_cc docker` image use `Ubuntu 18.04`. 
Doing tests, i tried to install `opencv` with `sudo apt-get install libopencv-dev` but the job stop in geographic area selection, job [attached](https://travis-ci.org/davidvelascogarcia/tensorflow-cpp-examples/builds/523833533).

**Comment by PeterBowman** [comment]
Please try `DEBIAN_FRONTEND=noninteractive apt-get install -y libopencv-dev` ([SO](https://stackoverflow.com/questions/44331836/apt-get-install-tzdata-noninteractive#comment91752692_44333806)).

**Comment by davidvelascogarcia** [comment]
@PeterBowman Thanks, works!

**Comment by PeterBowman** [comment]
Marked as WONTFIX, we are migrating now to GitHub Actions: https://github.com/roboticslab-uc3m/questions-and-answers/issues/91.
