### ISSUE TITLE
Remove Spanish version?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/developer-manual#27]
Maintaining 2 versions is becoming a blocking feature.

Remove Spanish version?

**Comment by jgvictores** [comment]
PS: It also involves **triplicates** of README, and ugly hacks with assets path.

**Comment by rsantos88** [comment]
For me I am agree to save the old version, for the flies :)

**Comment by PeterBowman** [comment]
> For me I am agree to save the old spanish version, for the flies :)

You really should raise your standards and keep the lab free of unwanted biological factors!

![pol_pl_packa-na-muchy-teleskopowa-26-72-cm-fackelmann-44678-4645_5](https://user-images.githubusercontent.com/9977198/35728972-8e0e5618-080d-11e8-8a4b-d6b754008c6a.jpg)

Joking aside, Spanish content does no (evident) harm, but it may set a cumbersome precedent since most other places (installation guides, SW/HW manuals, usage instructions, docs) are written in English.

**Comment by jgvictores** [comment]
Okay, I think this works!
![screenshot](https://user-images.githubusercontent.com/4448588/35729604-8caba2ba-080f-11e8-940b-110ee4f40179.png)

Closing issue!!
